[build]
  command = "npm ci --legacy-peer-deps --prefer-offline=false && npm run build"
  publish = "dist"

[dev]
  targetPort = 5173
  port = 8888
  autoLaunch = false

[functions]
  directory = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
package = "netlify-plugin-inline-functions-env"
  [plugins.inputs]
  include = ["KRAKEN_PRIVATE_KEY"]
