export const rewardLockTokenVaultAbi = [
  {
    type: 'constructor',
    inputs: [
      {
        name: '_liquidStakingAsset',
        type: 'address',
        internalType: 'contract IMetaPoolETH',
      },
      { name: '_owner', type: 'address', internalType: 'address' },
      {
        name: '_treasuryOwner',
        type: 'address',
        internalType: 'address',
      },
      {
        name: '_metaPoolOwner',
        type: 'address',
        internalType: 'address',
      },
      {
        name: '_projectTakeBps',
        type: 'uint16',
        internalType: 'uint16',
      },
      {
        name: '_metaPoolFeeBps',
        type: 'uint16',
        internalType: 'uint16',
      },
      {
        name: '_validLockDays',
        type: 'uint256[]',
        internalType: 'uint256[]',
      },
    ],
    stateMutability: 'nonpayable',
  },
  { type: 'receive', stateMutability: 'payable' },
  {
    type: 'function',
    name: 'addValidLockDurations',
    inputs: [{ name: '_days', type: 'uint256[]', internalType: 'uint256[]' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'applyPendingProjectTakeBps',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'closeTimestamp',
    inputs: [],
    outputs: [{ name: '', type: 'uint64', internalType: 'uint64' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getDeposit',
    inputs: [{ name: '_depositId', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      {
        name: '_deposit',
        type: 'tuple',
        internalType: 'struct Deposit',
        components: [
          {
            name: 'originalAmount',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'projectRewardsWithdrawn',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'ethAmount',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'lstExchangeRateAtCreation',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'lstExchangeRateAtUnlock',
            type: 'uint256',
            internalType: 'uint256',
          },
          { name: 'createdAt', type: 'uint64', internalType: 'uint64' },
          {
            name: 'lockDuration',
            type: 'uint64',
            internalType: 'uint64',
          },
          { name: 'isUnlocked', type: 'bool', internalType: 'bool' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getProjectAvailableRewards',
    inputs: [{ name: '_depositId', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      {
        name: '_availableAmount',
        type: 'uint256',
        internalType: 'uint256',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getRewardsDistribution',
    inputs: [{ name: '_depositId', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        internalType: 'struct RewardsDistribution',
        components: [
          {
            name: 'userAmount',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'projectAmount',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'totalRewards',
            type: 'uint256',
            internalType: 'uint256',
          },
          {
            name: 'exchangeRate',
            type: 'uint256',
            internalType: 'uint256',
          },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getUserDepositIds',
    inputs: [{ name: '_user', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256[]', internalType: 'uint256[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getValidLockDurations',
    inputs: [],
    outputs: [{ name: '', type: 'uint256[]', internalType: 'uint256[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'liquidStakingAsset',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'address',
        internalType: 'contract IMetaPoolETH',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'lock',
    inputs: [
      { name: '_amount', type: 'uint256', internalType: 'uint256' },
      { name: '_days', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [{ name: '_depositId', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'lockETH',
    inputs: [{ name: '_days', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '_depositId', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'metaPoolAvailableRewards',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'metaPoolFeeBps',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'metaPoolOwner',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'nextDepositId',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'openTimestamp',
    inputs: [],
    outputs: [{ name: '', type: 'uint64', internalType: 'uint64' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'pendingChange',
    inputs: [],
    outputs: [
      {
        name: 'newProjectTakeBps',
        type: 'uint16',
        internalType: 'uint16',
      },
      { name: 'activationTime', type: 'uint64', internalType: 'uint64' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'pendingToTransferTreasury',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'processRewards',
    inputs: [
      {
        name: 'depositIds_',
        type: 'uint256[]',
        internalType: 'uint256[]',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'projectAvailableRewards',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'projectTakeBps',
    inputs: [],
    outputs: [{ name: '', type: 'uint16', internalType: 'uint16' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'removeValidLockDurations',
    inputs: [{ name: '_days', type: 'uint256[]', internalType: 'uint256[]' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'renounceOwnership',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setLockingWindow',
    inputs: [
      {
        name: '_openTimestamp',
        type: 'uint64',
        internalType: 'uint64',
      },
      {
        name: '_closeTimestamp',
        type: 'uint64',
        internalType: 'uint64',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setProjectTakeBps',
    inputs: [
      {
        name: '_projectTakeBps',
        type: 'uint16',
        internalType: 'uint16',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'totalLockedAssets',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'totalUserDeposits',
    inputs: [{ name: '_user', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'totalUsers',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'transferOwnership',
    inputs: [{ name: 'newOwner', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'treasuryOwner',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'unlock',
    inputs: [{ name: '_depositId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'updateTreasury',
    inputs: [
      {
        name: '_treasuryOwner',
        type: 'address',
        internalType: 'address',
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'withdrawMetaPoolFees',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'withdrawProjectRewards',
    inputs: [],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'Lock',
    inputs: [
      {
        name: 'user',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'depositId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'lstAmount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'ethAmount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'exchangeRate',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'lockDuration',
        type: 'uint64',
        indexed: false,
        internalType: 'uint64',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'MetaPoolFeesWithdrawn',
    inputs: [
      {
        name: 'amount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'to',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'OwnershipTransferred',
    inputs: [
      {
        name: 'previousOwner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'newOwner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ProjectRewardsWithdrawn',
    inputs: [
      {
        name: 'amount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'to',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ProjectTakeChangeApplied',
    inputs: [
      {
        name: 'owner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'oldBps',
        type: 'uint16',
        indexed: false,
        internalType: 'uint16',
      },
      {
        name: 'newBps',
        type: 'uint16',
        indexed: false,
        internalType: 'uint16',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ProjectTakeChangeScheduled',
    inputs: [
      {
        name: 'owner',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'projectTakeBps',
        type: 'uint16',
        indexed: false,
        internalType: 'uint16',
      },
      {
        name: 'activationTime',
        type: 'uint64',
        indexed: false,
        internalType: 'uint64',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'RewardsProcessed',
    inputs: [
      {
        name: 'depositIds',
        type: 'uint256[]',
        indexed: false,
        internalType: 'uint256[]',
      },
      {
        name: 'totalProjectRewards',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'totalMetaPoolFees',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Unlock',
    inputs: [
      {
        name: 'user',
        type: 'address',
        indexed: true,
        internalType: 'address',
      },
      {
        name: 'depositId',
        type: 'uint256',
        indexed: true,
        internalType: 'uint256',
      },
      {
        name: 'userAmount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'projectAmount',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'totalRewards',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
      {
        name: 'exchangeRate',
        type: 'uint256',
        indexed: false,
        internalType: 'uint256',
      },
    ],
    anonymous: false,
  },
  { type: 'error', name: 'ChangeAlreadyPending', inputs: [] },
  { type: 'error', name: 'ChangeNotReady', inputs: [] },
  { type: 'error', name: 'DirectETHTransferNotAllowed', inputs: [] },
  {
    type: 'error',
    name: 'InvalidBps',
    inputs: [{ name: 'bps', type: 'uint16', internalType: 'uint16' }],
  },
  {
    type: 'error',
    name: 'InvalidLockingDuration',
    inputs: [{ name: 'duration', type: 'uint256', internalType: 'uint256' }],
  },
  { type: 'error', name: 'InvalidTimestamps', inputs: [] },
  { type: 'error', name: 'InvalidZeroAddress', inputs: [] },
  { type: 'error', name: 'InvalidZeroAmount', inputs: [] },
  { type: 'error', name: 'LockingNotOpen', inputs: [] },
  { type: 'error', name: 'MaxLockedPositions', inputs: [] },
  { type: 'error', name: 'NoPendingChange', inputs: [] },
  { type: 'error', name: 'NotDepositOwner', inputs: [] },
  { type: 'error', name: 'NotMetaPoolOwner', inputs: [] },
  { type: 'error', name: 'NotTreasuryOwner', inputs: [] },
  {
    type: 'error',
    name: 'OwnableInvalidOwner',
    inputs: [{ name: 'owner', type: 'address', internalType: 'address' }],
  },
  {
    type: 'error',
    name: 'OwnableUnauthorizedAccount',
    inputs: [{ name: 'account', type: 'address', internalType: 'address' }],
  },
  { type: 'error', name: 'PositionAlreadyUnlocked', inputs: [] },
  { type: 'error', name: 'PositionStillLocked', inputs: [] },
  {
    type: 'error',
    name: 'RecordNotFound',
    inputs: [{ name: 'recordId', type: 'uint256', internalType: 'uint256' }],
  },
  {
    type: 'error',
    name: 'SafeCastOverflowedUintDowncast',
    inputs: [
      { name: 'bits', type: 'uint8', internalType: 'uint8' },
      { name: 'value', type: 'uint256', internalType: 'uint256' },
    ],
  },
  {
    type: 'error',
    name: 'SafeERC20FailedOperation',
    inputs: [{ name: 'token', type: 'address', internalType: 'address' }],
  },
] as const;
